name: wakatime-stats

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '30 14 * * *' # runs at every 12AM UTC

jobs:
  update-readme:
    name: "build: update Readme with metrics"
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          COMMIT_BY_ME: "False"
          COMMIT_MESSAGE: "build: updated wakatime stats section"
          COMMIT_USERNAME: "akkaraponph"
          COMMIT_EMAIL: "akkaraponph@gmail.com"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.BD_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_COMMIT: "True"
          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_SHORT_INFO: "True"
